name: Bevin Richardson
favicon: null
layout_spectrum: 0.5871114083565772
typography_spectrum: 0.27639668248593807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c0c0a'
    - '#5e5433'
    - '#7b8e3b'
    - '#a0b241'
    - '#daca9a'
  brandStrength: 0.5001524307299405
  lightness: 0.08648311346769333
  saturation: 0.23422359209507704
  rhythmicContrast: 0.9702498936094344
purpose: []
