name: Bevin Richardson
favicon: null
layout_spectrum: 0.5871114083565772
typography_spectrum: 0.27639668248593807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5001524307299405
  lightness: 0.08648311346769333
  saturation: 0.23422359209507704
  rhythmicContrast: 0.9702498936094344
purpose: []
