analytics: {}
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#888888'
    - '#000000'
    - '#000000'
  brandStrength: 0.625
  lightness: 0.59009
  rhythmicContrast: 0.242117
  saturation: 0.474099
cta: {}
layout_spectrum: 0.746621
name: Bevin Richardson
opengraph: {}
purpose: []
typography_spectrum: 0.568693
